### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by k1ng440** [devsu/loopback-setup-remote-methods-mixin#1] opened 2016-12-12 18:23 UTC
Hello, i am getting following error on LB2

```
D:\projects\eleven\eleven-brain\node_modules\loopback-setup-remote-methods-mixin\setup-remote-methods.js:113
      Model.disableRemoteMethodByName(methodName);
            ^

TypeError: Model.disableRemoteMethodByName is not a function
    at methodsToDisable.forEach.methodName (D:\projects\eleven\eleven-brain\node_modules\loopback-setup-remote-methods-mixin\setup-remote-methods.js:113:13)
    at Array.forEach (native)
    at disableRemoteMethods (D:\projects\eleven\eleven-brain\node_modules\loopback-setup-remote-methods-mixin\setup-remote-methods.js:112:22)
    at processDisable (D:\projects\eleven\eleven-brain\node_modules\loopback-setup-remote-methods-mixin\setup-remote-methods.js:108:5)
    at EventEmitter.<anonymous> (D:\projects\eleven\eleven-brain\node_modules\loopback-setup-remote-methods-mixin\setup-remote-methods.js:26:9)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at Server.app.listen (D:\projects\eleven\eleven-brain\server\server.js:17:13)
    at Server.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1279:10)
    at D:\projects\eleven\eleven-brain\node_modules\async-listener\glue.js:188:31
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:122:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by c3s4r** [comment] 2016-12-12 21:22
Probably you are using an old Loopback version. What exact version of loopback are you using? On Sept. 22, 2016 disableRemoteMethod has been deprecated in favor of disableRemoteMethodByName.

https://github.com/strongloop/loopback/pull/2758/files
https://github.com/strongloop/loopback/pull/2758

And it has been back-ported to loopback 2:

https://github.com/strongloop/loopback/pull/2781

Anyways, if you want, you can contribute with a PR to support older versions of Loopback 2 ;)

**Comment by k1ng440** [comment] 2016-12-12 21:26
i am using `"loopback": "^2.22.0"`

sure. i will look into the code and contribute


thanks

**Comment by c3s4r** [comment] 2016-12-12 21:33
That's weird, I'm testing with "loopback": "^2.22.0", and it works fine. Probably you need to update your dependencies?

**Comment by c3s4r** [comment] 2017-02-13 13:47
Closing, since it couldn't be reproduced. Feel free to reopen including steps to reproduce if the error is still happening.

**Closed by c3s4r** 2017-02-13 13:47 UTC
