### ISSUE TITLE
Model.disableRemoteMethodByName is not a function

### ISSUE THREAD

**Issue by puttareddy** [devsu/loopback-setup-remote-methods-mixin#3] opened 2017-03-15 09:32 UTC
I am using loopback@ 2.22.0 and loopback-setup-remote-methods-mixin@ 1.0.3 with below configuration in my Model.json
"mixins": {
    "SetupRemoteMethods": {
      "ignoreACL": true,
      "disableAllExcept": []      
    }
  },
which is resulting me below error.
D:\workspace\loopback-app\node_modules\loopback-setup-remote-methods-mixin\setup-remote-methods.js:113
      Model.disableRemoteMethodByName(methodName);
            ^

TypeError: Model.disableRemoteMethodByName is not a function
    at methodsToDisable.forEach.methodName (D:\workspace\loopback-app\node_modules\loopback-setup-remote-methods-mixin\setup-remote-methods.js:113:13)
    at Array.forEach (native)
    at disableRemoteMethods (D:\workspace\loopback-app\node_modules\loopback-setup-remote-methods-mixin\setup-remote-methods.js:112:22)
    at processDisable (D:\workspace\loopback-app\node_modules\loopback-setup-remote-methods-mixin\setup-remote-methods.js:108:5)
    at EventEmitter.<anonymous> (D:\workspace\loopback-app\node_modules\loopback-setup-remote-methods-mixin\setup-remote-methods.js:26:9)
    at emitNone (events.js:86:13)
    at EventEmitter.emit (events.js:185:7)

Can you please help me to resolve this issue?

**Comment by c3s4r** [comment] 2017-04-10 15:59
This is a duplicate of https://github.com/devsu/loopback-setup-remote-methods-mixin/issues/1. See that issue for more info.

**Closed** 2018-07-17 03:39 UTC
